from aiogram.dispatcher.filters.state import StatesGroup, State

class end(StatesGroup):
    end_back_1_a = State()
    end_back_1_b = State()
    end_back_2_a = State()
    end_back_2_b = State()
    end_back_2_v = State()
    end_back_2_g = State()
    end_back_3_a = State()
    end_back_3_b = State()
    end_back_3_v = State()
    end_back_3_g = State()
    end_back_3_d = State()
    end_back_4_a = State()
    end_back_4_b = State()
    end_back_4_v = State()
    end_back_4_g = State()
    end_back_5_a = State()
    end_back_5_b = State()
    end_back_5_v = State()
    end_back_6_a = State()
    end_back_6_b = State()
    end_back_6_v = State()
    end_back_6_g = State()
    end_back_7_a = State()
    end_back_7_b = State()
    end_back_7_v = State()
    end_back_7_g = State()
    end_back_8_a = State()
    end_back_8_b = State()
    end_back_8_v = State()
    end_back_8_g = State()
    end_back_9_a = State()
    end_back_9_b = State()
    end_back_9_v = State()
    end_back_10_a = State()
    end_back_10_b = State()
    end_back_10_v = State()
    end_back_11_a = State()
    end_back_11_b = State()
    end_back_11_v = State()
    