from aiogram.dispatcher.filters.state import StatesGroup, State

class sinf_state(StatesGroup):
    sinf_1 = State()
    sinf_2 = State()
    sinf_3 = State()
    sinf_4 = State()
    sinf_5 = State()
    sinf_6 = State()
    sinf_7 = State()
    sinf_8 = State()
    sinf_9 = State()
    sinf_10 = State()
    sinf_11 = State()
    # admin panel start
    admin_panel_sinf_1 = State()
    admin_panel_sinf_2 = State()
    admin_panel_sinf_3 = State()
    admin_panel_sinf_4 = State()
    admin_panel_sinf_5 = State()
    admin_panel_sinf_6 = State()
    admin_panel_sinf_7 = State()
    admin_panel_sinf_8 = State()
    admin_panel_sinf_9 = State()
    admin_panel_sinf_10 = State()
    admin_panel_sinf_11 = State()